# # This workflow uses actions that are not certified by GitHub.
# # They are provided by a third-party and are governed by
# # separate terms of service, privacy policy, and support
# # documentation.

name: Dart

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2.12.0
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi

      # - name: Upload a build artifact
      #   uses: actions/upload-artifact@v4.0.0
      #   with:
      #     name: AndroidCICD.apk
      #     path: build/app/outputs/apk/debug/app-debug.apk
      - run: flutter build apk --release --split-per-abi

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/app/outputs/apk/release/*'
          tag: v0.0.33s
          token: ${{ secrets.DEPLOY_KEY}}
